# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "所有文章"
  url = "/posts/"
  title = ""
  weight = 1
[[main]]
  parent = "posts"
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 10
[[main]]
  parent = "posts"
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 20
[[main]]
  identifier = "life"
  pre = ""
  post = ""
  name = "生活"
  url = "/life/"
  title = ""
  weight = 2
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "系列"
  url = "/series/"
  title = ""
  weight = 3
[[main]]
  identifier = "heatmap"
  name = "热力图"
  url = "/heatmap/"
  pre = ""
  title = ""
  weight = 4
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "关于"
  url = "/about/"
  title = ""
  weight = 5
[[main]]
  parent = "about"
  identifier = "link"
  pre = ""
  post = ""
  name = "友链"
  url = "/link/"
  title = ""
  weight = 10
