# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
  weight = 1
[[main]]
  parent = "posts"
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 10
[[main]]
  parent = "posts"
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 20
[[main]]
  identifier = "life"
  pre = ""
  post = ""
  name = "Life"
  url = "/life/"
  title = ""
  weight = 2
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "Series"
  url = "/series/"
  title = ""
  weight = 3
[[main]]
  identifier = "heatmap"
  pre = ""
  post = ""
  name = "Heatmap"
  url = "/heatmap/"
  title = ""
  weight = 4
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
  weight = 5
