# Options to make output .md files
# 用于输出 Markdown 格式文档的设置

[MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[JsonFeed]
  mediaType = "application/feed+json"
  isPlainText = true
  notAlternative = true

[SearchIndexEn]
  mediaType = "application/json"
  baseName = "index.en"
  isPlainText = true
  notAlternative = true
  rel = "search"
  path = ""

[SearchIndexZhCn]
  mediaType = "application/json"
  baseName = "index.zh-cn"
  isPlainText = true
  notAlternative = true
  rel = "search"
  path = ""
