baseURL = "https://hugo.ybw051114.cf"
# [en, zh-cn, fr, ...] determines default content language
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
themesDir = "./themes"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

[languages]
  [languages.zh-cn]
    weight = 1
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    # 网站标题
    title = "Ybw051114"
    # 语言名称
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    # 默认每页列表显示的文章数目
    paginate = 12
    # [UA-XXXXXXXX-X] 谷歌分析代号
    googleAnalytics = ""
    # 版权描述，仅仅用于 SEO
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # 日期格式
    dateFormatToUse = "2006-01-02"
    # 菜单信息
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        pre = ""
        name = "所有文章"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        pre = ""
        name = "标签"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        pre = ""
        name = "分类"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.zh-cn.menu.main]]
        identifier = "documentation"
        pre = ""
        name = "文档"
        url = "/categories/documentation/"
        title = ""
        weight = 4
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        pre = ""
        name = "关于"
        url = "/about/"
        title = ""
        weight = 5
      [[languages.zh-cn.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/ybw051114/hugo-blog"
        title = "GitHub"
        weight = 6
    [languages.zh-cn.params]
      # 网站描述
      description = "Ybw051114 Blog"
      # 网站关键词
      keywords = ["OI", "Blog"]
      # 网站默认主题 ("light", "dark", "auto")
      defaultTheme = "auto"
      # 主页信息设置
      [languages.zh-cn.params.home]
        # 主页个人信息
        [languages.zh-cn.params.home.profile]
          enable = true
          # Gravatar 邮箱，用于优先在主页显示的头像
          gravatarEmail = "ybw051114@qq.com"
          # 主页显示头像的 URL
          avatarURL = "/images/avatar.png"
          # 主页显示的网站副标题
          subtitle = "一个蒟蒻、菜鸡的 OI 博客"
          # 是否为副标题显示打字机动画
          typeit = true
          # 是否显示社交账号
          social = true
        # 主页文章列表
        [languages.zh-cn.params.home.posts]
          enable = true
          # 主页每页显示文章数量
          paginate = 6
          # 当你没有在文章前面设置 "hiddenFromHomePage" 时的默认行为
          defaultHiddenFromHomePage = false
      # 主页的社交信息设置
      [languages.zh-cn.params.social]
        GitHub = "ybw051114"
        # Linkedin = "xxxx"
        # Twitter = "xxxx"
        # Instagram = "xxxx"
        Email = "ybw051114@qq.com"
        # Facebook = "xxxx"
        # Telegram = "xxxx"
        # Medium = "xxxx"
        # Gitlab = "xxxx"
        # Youtubelegacy = "xxxx"
        # Youtubecustom = "xxxx"
        # Youtubechannel = "xxxx"
        # Tumblr ="xxxx"
        # Quora = "xxxx"
        # Keybase = "xxxx"
        # Pinterest = "xxxx"
        # Reddit = "xxxx"
        # Codepen = "xxxx"
        # FreeCodeCamp = "xxxx"
        # Bitbucket = "xxxx"
        # Stackoverflow = "xxxx"
        # Weibo = "xxxx"
        # Odnoklassniki = "xxxx"
        # VK = "xxxx"
        # Flickr = "xxxx"
        # Xing = "xxxx"
        # Snapchat = "xxxx"
        # Soundcloud = "xxxx"
        # Spotify = "xxxx"
        # Bandcamp = "xxxx"
        # Paypal = "xxxx"
        # Fivehundredpx = "xxxx"
        # Mix = "xxxx"
        # Goodreads = "xxxx"
        # Lastfm = "xxxx"
        # Foursquare = "xxxx"
        # Hackernews = "xxxx"
        # Kickstarter = "xxxx"
        # Patreon = "xxxx"
        # Steam = "xxxx"
        # Twitch = "xxxx"
        # Strava = "xxxx"
        # Skype = "xxxx"
        # Whatsapp = "xxxx"
        # Zhihu = "xxxx"
        # Douban = "xxxx"
        # Angellist = "xxxx"
        # Slidershare = "xxxx"
        # Jsfiddle = "xxxx"
        # Deviantart = "xxxx"
        # Behance = "xxxx"
        # Dribble = "xxxx"
        # Wordpress = "xxxx"
        # Vine = "xxxx"
        # Googlescholar = "xxxx"
        # Researchgate = "xxxx"
        # Mastodon = "@xxxx"
        # MastodonPrefix = "https://mastodon.technology/"
        # Thingiverse = "xxxx"
        # Devto = "xxxx"
        # Gitea = "xxxx"
        # XMPP = "xxxx@example.com"
        # Matrix = "xxxx"
        Bilibili = "xxxx"
      # 文章页面的分享信息设置
      [languages.zh-cn.params.share]
        enable = true
        Twitter = true
        Facebook = true
        # Linkedin = true
        # Whatsapp = true
        # Pinterest = true
        # Tumblr = true
        # HackerNews = true
        # Reddit = true
        # VK = true
        # Buffer = true
        # Xing = true
        # Line = true
        # Instapaper = true
        # Pocket = true
        # Digg = true
        # Stumbleupon = true
        # Flipboard = true
        Weibo = true
        Renren = true
        # Myspace = true
        # Blogger = true
        Baidu = true
        # Odnoklassniki = true
        Evernote = true
        # Skype = true
        # Trello = true
        # Mix = true
      # 评论系统设置
      [languages.zh-cn.params.comment]
        enable = true
        # Disqus 评论系统设置 (https://disqus.com/)
        [languages.zh-cn.params.comment.disqus]
          # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
          shortname = ""
        # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
        [languages.zh-cn.params.comment.gitalk]
          owner = ""
          repo = ""
          clientId = ""
          clientSecret = ""
        # Valine 评论系统设置 (https://github.com/xCss/Valine)
        [languages.zh-cn.params.comment.valine]
          enable = true
          appId = "5AmQuQTF9mAg3M756Y7qUOnl-MdYXbMMI"
          appKey = "7ERhTLtbsWwR0i2lcsMuOEYI"
          placeholder = "你的评论 ..."
          notify = false
          verify = true
          avatar = "mp"
          meta= ""
          pageSize = 10
          lang = "zh-cn"
          visitor = true
          recordIP = true
        # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
        [languages.zh-cn.params.comment.facebook]
          enable = false
          width = "100%"
          numPosts = 10
          appId = ""
          languageCode = "zh_CN"

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.1.X"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/ybw051114/hugo-blog"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = "md5"
  # Header info
  # 页面头部导航栏信息
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  # 页面底部版权信息设置
  [params.footer]
    # Site creation time
    # 网站创立年份
    since = 2018
    # ICP info only in China (HTML format is allowed)
    # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
    icp = ""
    # license info (HTML format is allowed)
    # 许可协议信息 (允许使用 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Page config
  # 文章页面配置
  [params.page]
    # whether to use lightgallery in the page
    # 是否在文章页面使用 lightgallery
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
  # mathematical formulas (KaTeX https://katex.org/)
  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "xxxx"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40
  # Website Log Info just for SEO
  # 网站 Logo 信息，仅用于 SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  # 网站图标信息，仅用于 SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600
  # CSS and JS Files CDN
  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    # fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    # animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    # smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    # sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    # lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css">'
    lightgalleryJS = '<script src="https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/lib/js/lightgallery.min.js"></script>'
    lightgalleryThumbnailJS = '<script src="https://cdn.jsdelivr.net/npm/lg-thumbnail@1.1.0/dist/lg-thumbnail.min.js"></script>'
    lightgalleryZoomJS = '<script src="https://cdn.jsdelivr.net/npm/lg-zoom.js@1.0.1/dist/lg-zoom.min.js"></script>'
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    # typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    # katexCSS = ''
    # katexJS = ''
    # katexAutoRenderJS = ''
    # katexCopyTexCSS = ''
    # katexCopyTexJS = ''
    # katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    # mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    # aplayerCSS = ''
    # aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    # metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    # echartsJS = ''
    # echartsMacaronsJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    # gitalkCSS = ''
    # gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    # valineJS = ''
    fontawesomeFreeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">'
    animateCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.7.2/animate.min.css" integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous">'
    gitalkCSS = ''
    gitalkJS = ''
    valineJS = '<script src="https://cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js" integrity="sha256-zs7gKvw27wL9VQoC8Sq/3QV5BeeKpEOXSWdfzpYUiGE=" crossorigin="anonymous"></script>'
    lazysizesJS = '<script src="https://cdn.jsdelivr.net/npm/lazysizes@5.2.0/lazysizes.min.js" integrity="sha256-h2tMEmhemR2IN4wbbdNjj9LaDIjzwk2hralQwfJmBOE=" crossorigin="anonymous"></script>'
    smoothScrollJS = '<script src="https://cdn.jsdelivr.net/npm/smoothscroll-polyfill@0.4.4/dist/smoothscroll.min.js" integrity="sha256-Geq3csjLKRnRTVY3dLJJkZ9JiSlfVM9kRDRwyZZJMcQ=" crossorigin="anonymous"></script>'
    sharerJS = '<script src="https://cdn.jsdelivr.net/npm/share@0.7.40/dist/share.min.js" integrity="sha256-PQhHvZkRmMIi5qrTWKtHNUa4ZnSU+B811608xbeUmq8=" crossorigin="anonymous"></script>'
    katexCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha256-V8SV2MO1FUb63Bwht5Wx9x6PVHNa02gv8BgH/uH3ung=" crossorigin="anonymous">'
    katexJS = '<script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha256-F/Xda58SPdcUCr+xhSGz9MA2zQBPb0ASEYKohl8UCHc=" crossorigin="anonymous"></script>'
    katexAutoRenderJS = '<script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha256-90d2pnfw0r4K8CZAWPko4rpFXQsZvJhTBGYNkipDprI=" crossorigin="anonymous"></script>'
    katexCopyTexCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/copy-tex.min.css" integrity="sha256-v5/0E3/sOPYlVBnhQtCIPJxSCQiF10b4Du4SsnPZs+A=" crossorigin="anonymous">'
    katexCopyTexJS = '<script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/copy-tex.min.js" integrity="sha256-KrIjcykCG8RDmGyDJ/bmE1f7aKVOXSM9IkAjcYwCIH0=" crossorigin="anonymous"></script>'
    katexMhchemJS = '<script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/mathtex-script-type.min.js" integrity="sha256-b8diVEOgPDxUp0CuYCi7+lb5xIGcgrtIdrvE8d/oztQ=" crossorigin="anonymous"></script>'
    mermaidJS = '<script src="https://cdn.jsdelivr.net/npm/mermaid@8.4.7/dist/mermaid.core.min.js"></script>'
    echartsJS = '<script src="https://cdn.jsdelivr.net/npm/echarts@4.6.0/dist/echarts.simple.min.js" integrity="sha256-+hd5p1XvmiontyXydzMYjTGrmhSN20P3+y6FBc4cmAI=" crossorigin="anonymous"></script>'
    echartsMacaronsJS = '<script src="https://cdn.jsdelivr.net/npm/echarts-themes-js@1.0.2/src/macarons.js" integrity="sha256-Jn9+tn9wriXybJbdX4kfDTk31sNFofabjHrpcyt+XuU=" crossorigin="anonymous"></script>'
    typeitJS = '<script src="https://cdn.jsdelivr.net/npm/typeit@6.5.1/dist/typeit.min.js" integrity="sha256-4EdfrpcWtqmwQ1FIOj/SzSpC6asobaidLpfeXsvarI4=" crossorigin="anonymous"></script>'
    aplayerCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css" integrity="sha256-uqQQGnDcmRKvhKwc5Vm4XT1GQ2oV6t1U0NR2N9tV+BQ=" crossorigin="anonymous">'
    aplayerJS = '<script src="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js" integrity="sha256-6Y7CJDaltoeNgk+ZftgCD9jLgmGv4xKUo8nQ0HgAwVo=" crossorigin="anonymous"></script>'
    metingJS = '<script src="https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js" integrity="sha256-lOUP+l9qLbMTaCYKLNdL6sBZF+8JZrFxXmXrVbzSgj0=" crossorigin="anonymous"></script>'
    # themeJS='<script src="https://cdn.jsdelivr.net/gh/ybw051114/LoveIt@develop/src/js/theme.js"></script>'

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
# 作者信息
[author]
  name = "ybw051114"
  link = ""

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":sections/:filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
